# Generated by Django 4.2 on 2023-04-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemodel',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
